set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_ctl_in[0]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_ctl_in[0]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_char_is_k[0] -objects PciE/pcie_ptm_sniffer_tap/rx_ctl_in[0]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_ctl_in[1]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_ctl_in[1]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_char_is_k[1] -objects PciE/pcie_ptm_sniffer_tap/rx_ctl_in[1]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[0]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[0]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[0] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[0]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[1]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[1]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[1] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[1]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[2]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[2]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[2] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[2]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[3]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[3]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[3] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[3]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[4]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[4]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[4] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[4]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[5]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[5]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[5] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[5]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[6]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[6]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[6] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[6]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[7]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[7]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[7] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[7]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[8]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[8]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[8] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[8]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[9]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[9]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[9] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[9]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[10]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[10]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[10] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[10]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[11]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[11]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[11] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[11]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[12]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[12]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[12] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[12]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[13]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[13]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[13] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[13]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[14]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[14]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[14] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[14]
set pin_driver [get_nets -of [get_pins PciE/pcie_ptm_sniffer_tap/rx_data_in[15]]]
disconnect_net -net $pin_driver -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[15]
connect_net -hier -net PciE/pcie_s7/U0/inst/gt_top_i/pipe_rx0_data[15] -objects PciE/pcie_ptm_sniffer_tap/rx_data_in[15]