#!/bin/bash

declare -A node

#node1
#name of network namespace
node[1,0]='BC1'
#first ethernet
node[1,3]='eth0'
#firth ethernet IP
node[1,4]='192.168.1.2/24'


#node2
#name of network namespace
node[2,0]='BC2'
#first ethernet
node[2,1]='eth2'
#firth ethernet IP
node[2,2]='192.168.1.1/24'
#second ethernet
node[2,3]='eth3'
#second ethernet IP
node[2,4]='192.168.2.2/24'


#node3
#name of network namespace
node[3,0]='BC3'
#first ethernet
node[3,1]='eth4'
#firth ethernet IP
node[3,2]='192.168.2.1/24'
