#!/bin/bash

declare -A node

#node1
#name of network namespace
node[1,0]='BC1'
#first ethernet
node[1,1]='eth1p1'
#first ethernet IP
node[1,2]='192.168.0.1/24'
#second ethernet
node[1,3]='eth1p2'
#second ethernet IP
node[1,4]='192.168.1.2/24'


#node2
#name of network namespace
node[2,0]='BC2'
#first ethernet
node[2,1]='eth2p1'
#first ethernet IP
node[2,2]='192.168.1.1/24'
#second ethernet
node[2,3]='eth2p2'
#second ethernet IP
node[2,4]='192.168.2.2/24'


#node3
#name of network namespace
node[3,0]='BC3'
#first ethernet
node[3,1]='eth3p1'
#first ethernet IP
node[3,2]='192.168.2.1/24'
#second ethernet
node[3,3]='eth3p2'
#second ethernet IP
node[3,4]='192.168.3.2/24'


#node4
#name of network namespace
node[4,0]='BC4'
#first ethernet
node[4,1]='eth4p1'
#first ethernet IP
node[4,2]='192.168.3.1/24'
#second ethernet
node[4,3]='eth4p2'
#second ethernet IP
node[4,4]='192.168.4.2/24'


#node5
#name of network namespace
node[5,0]='BC5'
#first ethernet
node[5,1]='eth5p1'
#first ethernet IP
node[5,2]='192.168.4.1/24'
#second ethernet
node[5,3]='eth5p2'
#second ethernet IP
node[5,4]='192.168.5.2/24'


#node6
#name of network namespace
node[6,0]='BC6'
#first ethernet
node[6,1]='eth6p1'
#first ethernet IP
node[6,2]='192.168.5.1/24'
#second ethernet
node[6,3]='eth6p2'
#second ethernet IP
node[6,4]='192.168.6.2/24'


#node7
#name of network namespace
node[7,0]='BC7'
#first ethernet
node[7,1]='eth7p1'
#first ethernet IP
node[7,2]='192.168.6.1/24'
#second ethernet
node[7,3]='eth7p2'
#second ethernet IP
node[7,4]='192.168.7.2/24'
