#ifndef OSCILLATOR_MRO50_IOCTL_H
#define OSCILLATOR_MRO50_IOCTL_H

#define MRO50_MAGIC			'M'
#define READ_FINE			0x01
#define READ_COARSE			0x02
#define ADJUST_FINE			0x03
#define ADJUST_COARSE		0X04
#define READ_TEMP			0x05
#define READ_CTRL			0x06

#define MAX_PART_NAME		32

#define MRO50_READ_FINE		_IOR(MRO50_MAGIC, READ_FINE, u32 *)
#define MRO50_READ_COARSE	_IOR(MRO50_MAGIC, READ_COARSE, u32 *)
#define MRO50_ADJUST_FINE	_IOW(MRO50_MAGIC, ADJUST_FINE, u32)
#define MRO50_ADJUST_COARSE	_IOW(MRO50_MAGIC, ADJUST_COARSE, u32)
#define MRO50_READ_TEMP		_IOR(MRO50_MAGIC, READ_TEMP, u32 *)
#define MRO50_READ_CTRL		_IOR(MRO50_MAGIC, READ_CTRL, u32 *)


#endif // OSCILLATOR_MRO50_IOCTL_H